shamefullyHoist: true

allowBuilds:
  # post-install scripts required for correct behavior
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  # post-install scripts that can be ignored
  maplibre-gl: false
  puppeteer: false

minimumReleaseAgeExclude:
  # nuxt-ignis and its submodules must be excluded to allow 
  # installing latest version without cooldown
  - 'nuxt-ignis'
  - 'nuxt-spec'
  - '@nuxt-ignis/content'
  - '@nuxt-ignis/default'
  - '@nuxt-ignis/db'
  - '@nuxt-ignis/forms'
  - '@nuxt-ignis/ui'
  - '@nuxt-ignis/utils'
  - '@nuxt-ignis/validation'

overrides:
  # GHSA-g7r4-m6w7-qqqr & GHSA-gv7w-rqvm-qjhr
  'esbuild': '^0.28.1'
  # testing latest features
  'nuxt-spec': '0.2.4-alpha.2'  
