shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': true
  'sharp': true
  'unrs-resolver': true
  'esbuild': false
  'maplibre-gl': false
  'vue-demi': false

minimumReleaseAgeExclude:
  # nuxt-ignis and its submodules must be excluded to allow 
  # installing latest version without cooldown
  - 'nuxt-ignis'
  - 'nuxt-spec'
  - '@nuxt-ignis/content'
  - '@nuxt-ignis/default'
  - '@nuxt-ignis/db'
  - '@nuxt-ignis/forms'
  - '@nuxt-ignis/ui'
  - '@nuxt-ignis/utils'
  - '@nuxt-ignis/validation'

overrides:
  # will re-adjust later...
