export { useHead } from '#head';
export { isVue2, isVue3 } from 'vue-demi';
export { useAsyncData, useLazyAsyncData, refreshNuxtData, clearNuxtData, defineNuxtComponent, useNuxtApp, defineNuxtPlugin, useRuntimeConfig, useState, useFetch, useLazyFetch, useCookie, useRequestHeaders, useRequestEvent, setResponseStatus, setPageLayout, useRouter, useRoute, defineNuxtRouteMiddleware, navigateTo, abortNavigation, addRouteMiddleware, showError, clearError, isNuxtError, useError, createError, defineNuxtLink, useAppConfig, updateAppConfig, defineAppConfig, preloadComponents, preloadRouteComponents, prefetchComponents, loadPayload, preloadPayload, isPrerendered } from '#app';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, nextTick, provide, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState } from 'vue';
export { changeBaseAction, changeSpecificAction, changeBase, processInput } from '../composables/wbsc-eval';
export { default as wbscGlobal } from '../composables/wbsc-global';
export { getLabelForInputGroup, getLabelForRenderButton, renderPlayerOptions, renderHitLocationOptions, renderFCLocationOptions, renderBaseOptions, renderRunTypeOptions, renderBatterActionOptions, renderBatterRunnerActionOptions, renderRunnerActionOptions, renderBatterSpecificActionOptions, renderRunnerSpecificActionOptions } from '../composables/wbsc-html';
export { renderActionButtons, renderInputs } from '../composables/wbsc-input';
export { drawBackground, renderAction } from '../composables/wbsc-output';
export { processAction } from '../composables/wbsc-processor';
export { checkUserInput } from '../composables/wbsc-validation';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';