name: "Backstop tests"

on:
  workflow_dispatch:

jobs:
  backstop-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - name: Setup Nuxt app
          run: |
            npm install
            npm run build
            npm run start & npx wait-on http://127.0.0.1:3000
        - name: Run Backstop.js
          run: |
            npm run test
