name: "Backstop tests"

on:
  workflow_dispatch:

jobs:
  backstop-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - name: Setup Nuxt app
          run: |
            npm install
            npm run build
            npm run start & npx wait-on http://localhost:3000
        - name: Run Backstop.js
          run: |
            npm run test
        - name: Upload report
          uses: actions/upload-artifact@v3
          with:
            name: backstop_data
            path: /home/runner/work/WBSC-Scoring/WBSC-Scoring/backstop_data/
