on: 
  push:
    branches:
      - master
name: Deploy on push to master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v2
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: 115172.w72.wedos.net
        username: w115172
        password: ${{ secrets.ftp_password }}
        server-dir: www/wbsc
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          todo.txt